## Read Result


In [66]:
import pickle
import operator    
import re


In [15]:
with open('KNN.pickle', 'rb') as f:
    knn_small_result = pickle.load(f)
knn_small_value = [5, 10, 15, 20, 30]
print(knn_small_value)

with open('KNN_large.pickle', 'rb') as f:
    knn_large_result = pickle.load(f)
knn_large_value = [50, 80, 100, 150, 200]
print(knn_large_value)

with open('AAM.pickle', 'rb') as f:
    aam_small_result = pickle.load(f)
aam_small_value = [0.05, 0.08, 0.1, 0.12, 0.15, 0.2, 0.3]
print(aam_small_value)

with open('AAM_large.pickle', 'rb') as f:
    aam_large_result = pickle.load(f)
aam_large_value = [0.3, 0.35, 0.4, 0.45, 0.5, 0.6]
print(aam_large_value)


[5, 10, 15, 20, 30]
[50, 80, 100, 150, 200]
[0.05, 0.08, 0.1, 0.12, 0.15, 0.2, 0.3]
[0.3, 0.35, 0.4, 0.45, 0.5, 0.6]


### KNN

In [38]:
knn_value = np.array(knn_small_value + knn_large_value)

knn_ICH_concordance = np.array(list(knn_small_result[0]["ich"]) + list(knn_large_result[0]["ich"]))
knn_ICH_IPEC = np.array(list(knn_small_result[1]["ich"]) + list(knn_large_result[1]["ich"]))
knn_PAN_concordance = np.array(list(knn_small_result[0]["pancreatitis"]) + list(knn_large_result[0]["pancreatitis"]))
knn_PAN_IPEC = np.array(list(knn_small_result[1]["pancreatitis"]) + list(knn_large_result[1]["pancreatitis"]))

print("KNN - ICH:")
print("concordance:")
print(knn_ICH_concordance)
print("best on concordance:")
print("num_neighbors:", knn_value[np.argmax(knn_ICH_concordance)], "| concordance:", np.max(knn_ICH_concordance))
print("IPEC:")
print(knn_ICH_IPEC)
print("best on IPEC:")
print("num_neighbors:", knn_value[np.argmin(knn_ICH_IPEC)], "| IPEC:", np.min(knn_ICH_IPEC))
print()
print("KNN - PAN:")
print("concordance:")
print(knn_PAN_concordance)
print("best on concordance:")
print("num_neighbors:", knn_value[np.argmax(knn_PAN_concordance)], "| concordance:", np.max(knn_PAN_concordance))
print("IPEC:")
print(knn_PAN_IPEC)
print("best on IPEC:")
print("num_neighbors:", knn_value[np.argmin(knn_PAN_IPEC)], "| IPEC:", np.min(knn_PAN_IPEC))


KNN - ICH:
concordance:
[0.57290856 0.57612606 0.57530417 0.56948135 0.58170652 0.58092564
 0.58510561 0.58111874 0.58225224 0.58229836]
best on concordance:
num_neighbors: 80 | concordance: 0.5851056117113977
IPEC:
[0.20196752 0.1929608  0.1882102  0.18653157 0.1823965  0.18069443
 0.18058193 0.18090214 0.18094019 0.18195513]
best on IPEC:
num_neighbors: 80 | IPEC: 0.18058193441643783

KNN - PAN:
concordance:
[0.55698677 0.55374002 0.54550505 0.55404473 0.53507744 0.53583959
 0.51706758 0.51214502 0.50643675 0.49512578]
best on concordance:
num_neighbors: 5 | concordance: 0.5569867724867725
IPEC:
[0.20042575 0.19063042 0.18946486 0.18613778 0.18686605 0.18639645
 0.1862291  0.18628138 0.18528974 0.18542863]
best on IPEC:
num_neighbors: 150 | IPEC: 0.18528973831190673


In [43]:
knn_reduced_value = [5, 10, 20, 30]

with open('KNN_reduced.pickle', 'rb') as f:
    knn_reduced_result = pickle.load(f)

knn_reduced_ICH_concordance = knn_reduced_result[0]["ich"]
knn_reduced_ICH_IPEC = knn_reduced_result[1]["ich"]
knn_reduced_PAN_concordance = knn_reduced_result[0]["pancreatitis"]
knn_reduced_PAN_IPEC = knn_reduced_result[1]["pancreatitis"]

print("KNN reduced - ICH:")
print("concordance:")
print(knn_reduced_ICH_concordance)
print("best on concordance:")
print("num_neighbors:", knn_reduced_value[np.argmax(knn_reduced_ICH_concordance)], "| concordance:", np.max(knn_reduced_ICH_concordance))
print("IPEC:")
print(knn_reduced_ICH_IPEC)
print("best on IPEC:")
print("num_neighbors:", knn_reduced_value[np.argmin(knn_reduced_ICH_IPEC)], "| IPEC:", np.min(knn_reduced_ICH_IPEC))
print()
print("KNN reduced - PAN:")
print("concordance:")
print(knn_reduced_PAN_concordance)
print("best on concordance:")
print("num_neighbors:", knn_reduced_value[np.argmax(knn_reduced_PAN_concordance)], "| concordance:", np.max(knn_reduced_PAN_concordance))
print("IPEC:")
print(knn_reduced_PAN_IPEC)
print("best on IPEC:")
print("num_neighbors:", knn_reduced_value[np.argmin(knn_reduced_PAN_IPEC)], "| IPEC:", np.min(knn_reduced_PAN_IPEC))


KNN reduced - ICH:
concordance:
[0.5583288  0.57390694 0.57201429 0.58237818]
best on concordance:
num_neighbors: 30 | concordance: 0.5823781805507144
IPEC:
[0.20529676 0.19020538 0.18604094 0.1821032 ]
best on IPEC:
num_neighbors: 30 | IPEC: 0.18210319519593904

KNN reduced - PAN:
concordance:
[0.5222999  0.52967605 0.54137999 0.53658899]
best on concordance:
num_neighbors: 20 | concordance: 0.5413799903799904
IPEC:
[0.20986596 0.19562204 0.18784838 0.18615632]
best on IPEC:
num_neighbors: 30 | IPEC: 0.18615632233056156


### AAM

In [42]:
aam_value = np.array(aam_small_value + aam_large_value)

aam_ICH_concordance = np.array(list(aam_small_result[0]["ich"]) + list(aam_large_result[0]["ich"]))
aam_ICH_IPEC = np.array(list(aam_small_result[1]["ich"]) + list(aam_large_result[1]["ich"]))
aam_PAN_concordance = np.array(list(aam_small_result[0]["pancreatitis"]) + list(aam_large_result[0]["pancreatitis"]))
aam_PAN_IPEC = np.array(list(aam_small_result[1]["pancreatitis"]) + list(aam_large_result[1]["pancreatitis"]))

print("aam - ICH:")
print("concordance:")
print(aam_ICH_concordance)
print("best on concordance:")
print("coefficient:", aam_value[np.argmax(aam_ICH_concordance)], "| concordance:", np.max(aam_ICH_concordance))
print("IPEC:")
print(aam_ICH_IPEC)
print("best on IPEC:")
print("coefficient:", aam_value[np.argmin(aam_ICH_IPEC)], "| IPEC:", np.min(aam_ICH_IPEC))
print()
print("aam - PAN:")
print("concordance:")
print(aam_PAN_concordance)
print("best on concordance:")
print("coefficient:", aam_value[np.argmax(aam_PAN_concordance)], "| concordance:", np.max(aam_PAN_concordance))
print("IPEC:")
print(aam_PAN_IPEC)
print("best on IPEC:")
print("coefficient:", aam_value[np.argmin(aam_PAN_IPEC)], "| IPEC:", np.min(aam_PAN_IPEC))


aam - ICH:
concordance:
[0.55230464 0.56047392 0.56276844 0.55967189 0.56115418 0.56292866
 0.56468886 0.56498838 0.56818799 0.57070117 0.57044894 0.57171012
 0.57225793]
best on concordance:
coefficient: 0.6 | concordance: 0.5722579295921923
IPEC:
[0.3227908  0.31601842 0.31264407 0.30981338 0.30605018 0.30089251
 0.29305255 0.29307663 0.2902858  0.2878678  0.28573394 0.28390186
 0.2808304 ]
best on IPEC:
coefficient: 0.6 | IPEC: 0.28083039626243467

aam - PAN:
concordance:
[0.51003102 0.51026888 0.51023882 0.51038023 0.50981145 0.51010101
 0.51154954 0.51088408 0.51053632 0.50974098 0.51029846 0.51018038
 0.51051034]
best on concordance:
coefficient: 0.3 | concordance: 0.5115495430495431
IPEC:
[0.37874723 0.37822824 0.37788626 0.37757223 0.377136   0.37642502
 0.37527073 0.37526597 0.37451314 0.37386782 0.37324159 0.37266741
 0.37170037]
best on IPEC:
coefficient: 0.6 | IPEC: 0.37170036808656376


In [45]:
aam_reduced_value = [0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6]

with open('aam_reduced.pickle', 'rb') as f:
    aam_reduced_result = pickle.load(f)

aam_reduced_ICH_concordance = aam_reduced_result[0]["ich"]
aam_reduced_ICH_IPEC = aam_reduced_result[1]["ich"]
aam_reduced_PAN_concordance = aam_reduced_result[0]["pancreatitis"]
aam_reduced_PAN_IPEC = aam_reduced_result[1]["pancreatitis"]

print("aam reduced - ICH:")
print("concordance:")
print(aam_reduced_ICH_concordance)
print("best on concordance:")
print("coefficient:", aam_reduced_value[np.argmax(aam_reduced_ICH_concordance)], "| concordance:", np.max(aam_reduced_ICH_concordance))
print("IPEC:")
print(aam_reduced_ICH_IPEC)
print("best on IPEC:")
print("coefficient:", aam_reduced_value[np.argmin(aam_reduced_ICH_IPEC)], "| IPEC:", np.min(aam_reduced_ICH_IPEC))
print()
print("aam reduced - PAN:")
print("concordance:")
print(aam_reduced_PAN_concordance)
print("best on concordance:")
print("coefficient:", aam_reduced_value[np.argmax(aam_reduced_PAN_concordance)], "| concordance:", np.max(aam_reduced_PAN_concordance))
print("IPEC:")
print(aam_reduced_PAN_IPEC)
print("best on IPEC:")
print("coefficient:", aam_reduced_value[np.argmin(aam_reduced_PAN_IPEC)], "| IPEC:", np.min(aam_reduced_PAN_IPEC))


aam reduced - ICH:
concordance:
[0.58414035 0.5841314  0.58436703 0.58437516 0.58359905 0.58420995
 0.58471349 0.58421087]
best on concordance:
coefficient: 0.5 | concordance: 0.5847134890205646
IPEC:
[0.18481743 0.18481816 0.18481889 0.18481963 0.18482113 0.18482264
 0.18482417 0.18482572]
best on IPEC:
coefficient: 0.05 | IPEC: 0.18481743252593397

aam reduced - PAN:
concordance:
[0.52033502 0.51880303 0.5187696  0.51927393 0.51919841 0.52277201
 0.52176696 0.52185762]
best on concordance:
coefficient: 0.4 | concordance: 0.5227720057720058
IPEC:
[0.18296542 0.18296706 0.18296874 0.18297047 0.18297405 0.1829778
 0.18298173 0.18298582]
best on IPEC:
coefficient: 0.05 | IPEC: 0.1829654174321154


### with standard scaling


In [100]:
aam_reduced_value = [0.05, 0.5]

with open('AAM_results/AAM_std_reduced.pickle', 'rb') as f:
    aam_reduced_result = pickle.load(f)

aam_reduced_ICH_concordance = aam_reduced_result[0]["ich"]
aam_reduced_ICH_IPEC = aam_reduced_result[1]["ich"]
aam_reduced_PAN_concordance = aam_reduced_result[0]["pancreatitis"]
aam_reduced_PAN_IPEC = aam_reduced_result[1]["pancreatitis"]

print("aam reduced - ICH:")
print("concordance:")
print(aam_reduced_ICH_concordance)
print("best on concordance:")
print("coefficient:", aam_reduced_value[np.argmax(aam_reduced_ICH_concordance)], "| concordance:", np.max(aam_reduced_ICH_concordance))
print("IPEC:")
print(aam_reduced_ICH_IPEC)
print("best on IPEC:")
print("coefficient:", aam_reduced_value[np.argmin(aam_reduced_ICH_IPEC)], "| IPEC:", np.min(aam_reduced_ICH_IPEC))
print()
print("aam reduced - PAN:")
print("concordance:")
print(aam_reduced_PAN_concordance)
print("best on concordance:")
print("coefficient:", aam_reduced_value[np.argmax(aam_reduced_PAN_concordance)], "| concordance:", np.max(aam_reduced_PAN_concordance))
print("IPEC:")
print(aam_reduced_PAN_IPEC)
print("best on IPEC:")
print("coefficient:", aam_reduced_value[np.argmin(aam_reduced_PAN_IPEC)], "| IPEC:", np.min(aam_reduced_PAN_IPEC))


aam reduced - ICH:
concordance:
[0.5794688  0.58824399]
best on concordance:
coefficient: 0.5 | concordance: 0.5882439874520738
IPEC:
[0.18473885 0.18472905]
best on IPEC:
coefficient: 0.5 | IPEC: 0.1847290468300177

aam reduced - PAN:
concordance:
[0.5515303  0.55273401]
best on concordance:
coefficient: 0.5 | concordance: 0.5527340067340067
IPEC:
[0.19016433 0.19006296]
best on IPEC:
coefficient: 0.5 | IPEC: 0.19006296248174048


###  RSF

#### reduced


In [89]:
n_components = 25 # without standard scale
RSF_reduced_n_trees = [20, 50, 100]
RSF_reduced_max_features = [10, 20]
RSF_reduced_max_depths = [3, 6, 10]

with open('RSF_results/RSF_reduced_part.pickle', 'rb') as f:
    RSF_reduced_result = pickle.load(f)

RSF_reduced_dict = {}
for n_tree in RSF_reduced_n_trees:
    for row, max_feature in enumerate(RSF_reduced_max_features):
        for col, max_depth in enumerate(RSF_reduced_max_depths):
            RSF_reduced_dict[(n_tree, max_feature, max_depth)] = {
                "conc_PAN": RSF_reduced_result[0]["pancreatitis"][n_tree][row][col],
                "conc_ICH": RSF_reduced_result[0]["ich"][n_tree][row][col],
                "ipec_PAN": RSF_reduced_result[1]["pancreatitis"][n_tree][row][col],
                "ipec_ICH": RSF_reduced_result[1]["ich"][n_tree][row][col]                
            }
                
RSF_reduced_PAN_concordance_best = max(RSF_reduced_dict.items(), key=lambda x:x[1]["conc_PAN"])
RSF_reduced_ICH_concordance_best = max(RSF_reduced_dict.items(), key=lambda x:x[1]["conc_ICH"])
RSF_reduced_PAN_IPEC_best = min(RSF_reduced_dict.items(), key=lambda x:x[1]["ipec_PAN"])
RSF_reduced_ICH_IPEC_best = min(RSF_reduced_dict.items(), key=lambda x:x[1]["ipec_ICH"])

print("RSF reduced - PAN:")
print("best on concordance:")
print("n_tree, max_feature, max_depth:", RSF_reduced_PAN_concordance_best[0], "| concordance:", RSF_reduced_PAN_concordance_best[1]["conc_PAN"])
print("best on IPEC:")
print("n_tree, max_feature, max_depth:", RSF_reduced_PAN_IPEC_best[0], "| IPEC:", RSF_reduced_PAN_IPEC_best[1]["ipec_PAN"])
print()
# print("RSF reduced - ICH:")
# print("best on concordance:")
# print("n_tree, max_feature, max_depth:", RSF_reduced_ICH_concordance_best[0], "| concordance:", RSF_reduced_ICH_concordance_best[1]["conc_ICH"])
# print("best on IPEC:")
# print("n_tree, max_feature, max_depth:", RSF_reduced_ICH_IPEC_best[0], "| IPEC:", RSF_reduced_ICH_IPEC_best[1]["ipec_ICH"])


RSF reduced - PAN:
best on concordance:
n_tree, max_feature, max_depth: (100, 10, 10) | concordance: 0.5535233285233284
best on IPEC:
n_tree, max_feature, max_depth: (50, 10, 3) | IPEC: 0.18245796979866122



#### without reduction


In [95]:
RSF_n_trees = [20, 50]
RSF_max_features = [10, 20, 40, 60, 80, 200]
RSF_max_depths = [5, 10, 15]
RSF_dict = {}

with open('RSF_results/RSF.out', 'r') as f:
    dataset = 'PAN'
    n_tree = 20
    max_feature = 10
    max_depth = 5
    for line in f:
        if re.match(r'For the ich dataset:', line):
            dataset = 'ICH'
            continue
        if re.match(r'\[LOG\] n_tree', line):
            tokens = line.split(" = ")
            n_tree = int(tokens[1].split(",")[0])
            max_feature = int(tokens[2].split(",")[0])
            max_depth = int(tokens[3].split("\n")[0])
            if (n_tree, max_feature, max_depth) not in RSF_dict:
                RSF_dict[(n_tree, max_feature, max_depth)] = {}
        if re.match(r'\[LOG\] avg\. concordance', line):
            concordance = float(line.split(": ")[1])
            RSF_dict[(n_tree, max_feature, max_depth)]["conc_" + dataset] = concordance
        if re.match(r'\[LOG\] avg\. ipec', line):
            ipec_score = float(line.split(": ")[1])
            RSF_dict[(n_tree, max_feature, max_depth)]["ipec_" + dataset] = ipec_score
 

In [96]:
RSF_PAN_concordance_best = max(RSF_dict.items(), key=lambda x:x[1]["conc_PAN"])
RSF_ICH_concordance_best = max(RSF_dict.items(), key=lambda x:x[1]["conc_ICH"])
RSF_PAN_IPEC_best = min(RSF_dict.items(), key=lambda x:x[1]["ipec_PAN"])
RSF_ICH_IPEC_best = min(RSF_dict.items(), key=lambda x:x[1]["ipec_ICH"])

print("RSF reduced - PAN:")
print("best on concordance:")
print("n_tree, max_feature, max_depth:", RSF_PAN_concordance_best[0], "| concordance:", RSF_PAN_concordance_best[1]["conc_PAN"])
print("best on IPEC:")
print("n_tree, max_feature, max_depth:", RSF_PAN_IPEC_best[0], "| IPEC:", RSF_PAN_IPEC_best[1]["ipec_PAN"])
print()
print("RSF reduced - ICH:")
print("best on concordance:")
print("n_tree, max_feature, max_depth:", RSF_ICH_concordance_best[0], "| concordance:", RSF_ICH_concordance_best[1]["conc_ICH"])
print("best on IPEC:")
print("n_tree, max_feature, max_depth:", RSF_ICH_IPEC_best[0], "| IPEC:", RSF_ICH_IPEC_best[1]["ipec_ICH"])


RSF reduced - PAN:
best on concordance:
n_tree, max_feature, max_depth: (50, 20, 10) | concordance: 0.559587542087542
best on IPEC:
n_tree, max_feature, max_depth: (50, 40, 5) | IPEC: 0.18194392586255279

RSF reduced - ICH:
best on concordance:
n_tree, max_feature, max_depth: (20, 10, 5) | concordance: 0.586682119205298
best on IPEC:
n_tree, max_feature, max_depth: (20, 80, 5) | IPEC: 0.18125757444497248


### COX


In [97]:
cox_value = [0.05, 0.07, 0.09, 0.1, 0.11, 0.13, 0.15]

with open('COX_results/cox.pickle', 'rb') as f:
    cox_result = pickle.load(f)

cox_ICH_concordance = cox_result[0]["ich"]
cox_ICH_IPEC = cox_result[1]["ich"]
cox_PAN_concordance = cox_result[0]["pancreatitis"]
cox_PAN_IPEC = cox_result[1]["pancreatitis"]

print("cox reduced - ICH:")
print("concordance:")
print(cox_ICH_concordance)
print("best on concordance:")
print("coefficient:", cox_value[np.argmax(cox_ICH_concordance)], "| concordance:", np.max(cox_ICH_concordance))
print("IPEC:")
print(cox_ICH_IPEC)
print("best on IPEC:")
print("coefficient:", cox_value[np.argmin(cox_ICH_IPEC)], "| IPEC:", np.min(cox_ICH_IPEC))
print()
print("cox reduced - PAN:")
print("concordance:")
print(cox_PAN_concordance)
print("best on concordance:")
print("coefficient:", cox_value[np.argmax(cox_PAN_concordance)], "| concordance:", np.max(cox_PAN_concordance))
print("IPEC:")
print(cox_PAN_IPEC)
print("best on IPEC:")
print("coefficient:", cox_value[np.argmin(cox_PAN_IPEC)], "| IPEC:", np.min(cox_PAN_IPEC))


cox reduced - ICH:
concordance:
[0. 0. 0. 0. 0. 0. 0.]
best on concordance:
coefficient: 0.05 | concordance: 0.0
IPEC:
[0. 0. 0. 0. 0. 0. 0.]
best on IPEC:
coefficient: 0.05 | IPEC: 0.0

cox reduced - PAN:
concordance:
[0.55791775 0.54735979 0.         0.         0.         0.
 0.        ]
best on concordance:
coefficient: 0.05 | concordance: 0.5579177489177489
IPEC:
[0.18716509 0.18555782 0.         0.         0.         0.
 0.        ]
best on IPEC:
coefficient: 0.09 | IPEC: 0.0
